### ISSUE TITLE
!AutoAssist Attribute Error: module includeIpInSystemMessageTemp

### ISSUE THREAD

**Issue by heijligers** [eliranwong/letmedoit#23]
`Traceback (most recent call last):
  File "/Users/datascience/PycharmProjects/github/letmedoit/venv/lib/python3.11/site-packages/letmedoit-2.0.56-py3.11.egg/letmedoit/autoassist.py", line 119, in run
    self.getResponse(message, auto)
  File "/Users/datascience/PycharmProjects/github/letmedoit/venv/lib/python3.11/site-packages/letmedoit-2.0.56-py3.11.egg/letmedoit/autoassist.py", line 47, in getResponse
    {SharedUtil.getDeviceInfo()}
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/datascience/PycharmProjects/github/letmedoit/venv/lib/python3.11/site-packages/letmedoit-2.0.56-py3.11.egg/letmedoit/utils/shared_utils.py", line 477, in getDeviceInfo
    if config.includeIpInSystemMessageTemp or includeIp or (config.includeIpInSystemMessage and config.includeIpInSystemMessageTemp):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'letmedoit.config' has no attribute 'includeIpInSystemMessageTemp'`

**Comment by eliranwong** [comment]
fixed in this commit https://github.com/eliranwong/letmedoit/commit/cfc72a4b981d77def812e5e0689f1b2ffeaae3c1

pip version v2.0.57

thanks for reporting the issue
