### ISSUE TITLE
cant  do shit!  help?

### ISSUE THREAD

**Issue by VinceYannini** [eliranwong/letmedoit#62]
Error: Issue on OpenAI side.
Solution: Retry your request after a brief wait and contact us if the issue persists.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/vwolf/micromamba/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/vwolf/micromamba/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vwolf/micromamba/lib/python3.9/site-packages/letmedoit/utils/streaming_word_wrapper.py", line 122, in streamOutputs
    answer = event.choices[0].delta.content
AttributeError: 'str' object has no attribute 'choices'

**Comment by eliranwong** [comment]
things are changing, we are upgrading to version 3.0 https://github.com/eliranwong/letmedoit/issues/63
